### ISSUE TITLE
Define business requirements and objectives

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#1]
As a **developer** I can **understand the business requirements** so that I can **create a valuable business tool**.

**Acceptance Criteria**
- [x] The business requirements and objectives should be clearly defined and understood.
- [x] The above will be documented.

**Tasks**
- [x] Meet with the client to discuss the business requirements and objectives.
- [x] Define the inputs and outputs.
- [x] Document the business requirements and objectives

**Comment by alanjameschapman** [comment]
All business requirements and objectives have be clearly defined, understood and documented in the README.

The model's inputs are images of animals and the intended outputs are the species of the animals, along with key info and common diseases based on the animal.
