### ISSUE TITLE
Perform and document manual testing

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#10]
As a **developer** I can **manually test** so that I can **check that business requirements have been met**.

**Acceptance Criteria**
- [ ] All user stories have been checked.

**Tasks**
- [x] Test user stories.
- [x] Test input validation.
- [x] Test responsiveness.
- [x] Test browser compatibility.
