### ISSUE TITLE
Identify animal from an uploaded image

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#11]
As a **consultant** I can **identify the animal from an uploaded image** so that I can **prepare for the consultation**.

**Acceptance Criteria**
- [x] Model can correctly predict with 95% accuracy.

**Tasks**
- [x] Provide an image upload widget on deployed pipeline and dashboard.
- [x] Display prediction on dashboard.

**Comment by alanjameschapman** [comment]
The best accuracy achieved was around 80%. Whilst this failed to meet the 95% target, it was enough to provide the functionality required by the client of providing the top 3 breeds based on probability.
