### ISSUE TITLE
Identify whether the image is a dog or not

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#15]
As a **user** I can **be notified if the image is not a dog** so that I can **get value from the tool**.

**Acceptance Criteria**
- [ ] Model predicts that image is not a dog with a high degree of certainty

**Tasks**
- [ ] Set threshold value(s) for dog breed prediction.
- [ ] If threshold not met, user notified.
