### ISSUE TITLE
Define success criteria

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#2]
As a **developer** I can **define the success criteria for the project** so that I can **manage the client's expectations**.

**Acceptance Criteria**
- [x] The success criteria should be clearly defined and agreed upon with the client.

**Tasks**
- [x] Define the success criteria for the project.
- [x] Review and finalize the success criteria with the client.

**Comment by alanjameschapman** [comment]
The success criteria have been clearly defined, agreed upon with the client and documented in the README.
