### ISSUE TITLE
Collect the dataset

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#3]
As a **developer** I can **collect the dataset of animals images** so that I can **plan how I might achieve the business objectives**.

**Acceptance Criteria**
- [x] The dataset should contain images of various species and breeds of animals, as agreed with the client
- [x] The images should be of sufficient quality and quantity to train the model.

**Tasks**
- [x] Download the dataset from Kaggle.
- [x] Explore the dataset to understand its structure and contents.
- [x] Run statistical tests and visualise the dataset.

**Comment by alanjameschapman** [comment]
The dataset was reviewed with the client to identify if there were any missing animals. The following dog breeds were identified:
- Springer spaniel
- Border collie
- Jack russell terrier
- Pugs.

The client was satisfied that the dataset was not deficient in any other animal that was commonly seen during consults.

**Comment by alanjameschapman** [comment]
Images of the aforementioned dog breeds were added to the dataset.

The dataset was checked for quantity and quality:

| Quantity | Quality |
| - | - |
| ![Image](https://github.com/alanjameschapman/pet-image-classifier/assets/137620143/8130687d-8f44-4e62-a4ac-b0289b78597c) | ![Image](https://github.com/alanjameschapman/pet-image-classifier/assets/137620143/907070f0-966a-4a80-ac07-a17ded2bb3f6) |

**Quantity**
The majority of animals have between 27 and 30 images, which is anticipated as being enough to train the model. There is some variation either side of this (minimum = 17, maximum = 49), but it is anticipated that any bias can be removed at the next step. If there is difficulty training the model with this dataset, this will be rectified as required.

**Quality**
The minimum resolution across all images is 100 x 100px. Visually, the image appears to be recognisable as a great dane and therefore deemed acceptable:

![Image](https://github.com/alanjameschapman/pet-image-classifier/assets/137620143/80f64801-cc81-4cb1-af3c-2e9bd156e9f5)

The resolution of many of the images will likely be higher than required. Resolution can be reduced at the next step (#4) to improve the efficiency and speed of the ML pipeline.

**Comment by alanjameschapman** [comment]
See readme for updated graphics due to revised dataset
