### ISSUE TITLE
Pre-process images

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#4]
As a **developer** I can **preprocess the images** so that I can **prepare them for training**.

**Acceptance Criteria**
- [x] All images should be labelled, resized and normalized to a standard size (LO 3.1).
- [x] Datasets for each animal should have similar number of images to avoid bias.

**Tasks**
- [x] Check and ensure similar number of images per animal.
- [x] Resize and rename the images.

**Comment by alanjameschapman** [comment]
Tasks moved to issue #6:
- Extract relevant features on which to train the model.
- Augment and engineer features.
