### ISSUE TITLE
Split the images into sets

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#5]
As a **developer** I can **split the images into training, validation, and test sets** so that I can **optimise a model which generalizes well to new, unseen data**.

**Acceptance Criteria**
- [x] Image sets should initially be 70% training, 15% validation, and 15% test.

**Tasks**
- [x] Split the images into training, validation, and test sets.
- [x] Plot the numbers of images in each set (LO 3.1).

**Comment by alanjameschapman** [comment]
![Image](https://github.com/alanjameschapman/pet-image-classifier/assets/137620143/d666a3fc-3d49-4f84-a079-1bc44814a520)
