### ISSUE TITLE
Evaluate the model

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#7]
As a **developer** I can **evaluate the model** so that I can **deploy the pipeline for feedback**.

**Acceptance Criteria**
- [x] Business success criteria are met - **otherwise, return to #6**.

**Tasks**
- [x] Evaluate the model's accuracy on the test set.
- [x] Validate and visualise the model's performance on the test set using a confusion matrix and Scikit Learn report (LO 5.2).
