### ISSUE TITLE
Create a dashboard

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#8]
As a **developer** I can **create a dashboard** so that I can **display the results of the image classifier**.

**Acceptance Criteria**
- [x] Dashboard should display the results of the image classifier.
- [x] Business success criteria are met.

**Tasks**
- [x] Design the layout of the dashboard, listing the pages and content and how they relate to the business requirements (LO 6.1).
- [x] Implement the image classifier in the dashboard.
