### ISSUE TITLE
Plan monitoring and maintenance of the model

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/pet-image-classifier#9]
As a **developer** I can **plan monitoring and maintenance of the model** so that I can **ensure the business tool retains value to the client**.

**Acceptance Criteria**
- [ ] Monitoring and maintenance plan is documented.
- [ ] Business tool retains value to the client.

**Tasks**
- [ ] Discuss and formulate a plan with the client.
- [ ] Document the plan with the client.
- [ ] Report all project findings.
